net9 packages and reading a file was not working (#234)
Result: Function 'Watermark', Invocation id '9e8686f7-354b-43a7-b2c4-7aa281099ca8': An exception was thrown by the invocation.
Exception: System.IO.FileNotFoundException: The file resources/watermark.png does not exist.

Co-authored-by: Federico Arambarri <v-fearam>